# Welcome to Jekyll!
#

# Site settings
title: Theiss Bendixen
description: |
  PhD\\
  Psykolog\\
  Forfatter\\
  Konsulent  
owner: Theiss Bendixen
first_published: 2023
email: tb@theissbendixen.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://theissbendixen.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/Theiss_Bendixen
  linkedin-square: https://www.linkedin.com/in/theiss-bendixen-81015462/
  facebook-official: https://www.facebook.com/theiss.bendixen
  instagram: https://www.instagram.com/theissbendixen/
  google-plus-square: https://scholar.google.com/citations?user=KODTe8oAAAAJ&hl=da
  github: https://github.com/tbendixen
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
